name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-20.04
    container: node:18-bullseye-slim

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies
      # in the `package.json` file
      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
